stages:
  - install_deps
  - depoly

cache:
  paths:
    - node_modules/

install_deps:
  stage: install_deps
  script:
    - npm i --no-optional
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^qatest/'
    - if: '$CI_COMMIT_BRANCH =~ /^pre-release/'
    - if: '$CI_COMMIT_TAG'
  tags:
    - node:12.14

depoly_qa:
  stage: depoly
  script:
    - devops dp --buildCommand=build:qa
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^qatest/'
  tags:
    - node:12.14

depoly_pre:
  stage: depoly
  script:
    - devops dp --buildCommand=build:pre
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^pre-release/'
  tags:
    - node:12.14

depoly:
  stage: depoly
  script:
    - devops dp
  rules:
    - if: '$CI_COMMIT_TAG'
  tags:
    - node:12.14
